name: ci-cd
run-name: ${{ github.actor }} is running ci-cd 
on: [push]
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip3 install -r requirements.txt